name: CI
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  build-test-lint-typecheck:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2 # If you're using actions/checkout@v2 you must set persist-credentials to false in most cases for the deployment to work correctly.
      - uses: actions/setup-node@v2-beta
        with:
          node-version: '14'
        env:
          NEXT_PUBLIC_SANITY_PROJECT_ID: ${{ secrets.NEXT_PUBLIC_SANITY_PROJECT_ID }}
          SANITY_API_TOKEN: ${{ secrets.SANITY_API_TOKEN }}
          SANITY_PREVIEW_SECRET: ${{ secrets.SANITY_PREVIEW_SECRET }}
      - run: echo 'NEXT_PUBLIC_SANITY_PROJECT_ID=$NEXT_PUBLIC_SANITY_PROJECT_ID\nSANITY_API_TOKEN=$SANITY_API_TOKEN\nSANITY_PREVIEW_SECRET=$SANITY_PREVIEW_SECRET' >> .env
      - run: yarn install
      - run: yarn build
      - run: yarn lint
      - run: yarn typecheck
